# Generated by Django 4.2.10 on 2024-02-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rst_no', models.IntegerField()),
                ('net_wt', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
