# Generated by Django 4.2.10 on 2024-02-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
    ]
