# Generated by Django 4.2.10 on 2024-02-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rst_no_p', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=10)),
                ('net_wt_p', models.IntegerField()),
            ],
        ),
    ]
