# Generated by Django 4.2.10 on 2024-02-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0002_productionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionmodel',
            old_name='net_wt_p',
            new_name='product_net_weight',
        ),
        migrations.RenameField(
            model_name='productionmodel',
            old_name='rst_no_p',
            new_name='product_rst',
        ),
    ]
