# Generated by Django 4.2.10 on 2024-02-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0002_invoice_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
