# Generated by Django 5.0.2 on 2024-03-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0002_alter_invoicemodel_item_45mm_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialmodel',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
