# Generated by Django 5.0.2 on 2024-03-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0003_rawmaterialmodel_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialmodel',
            name='kanta_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
