# Generated by Django 4.2.10 on 2024-02-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0003_delete_invoice_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmodel',
            name='product_rst',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialmodel',
            name='rst_no',
            field=models.IntegerField(unique=True),
        ),
    ]
