# Generated by Django 4.2.10 on 2024-02-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0004_alter_productionmodel_product_rst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalgoods',
            old_name='product_description',
            new_name='item',
        ),
        migrations.AddField(
            model_name='finalgoods',
            name='total',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=8),
            preserve_default=False,
        ),
    ]
