# Generated by Django 4.2.10 on 2024-02-12 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
