# Generated by Django 5.0.2 on 2024-03-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0004_rawmaterialmodel_kanta_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawExpense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('labour', 'labour'), ('diesel', 'diesel')], max_length=20)),
                ('description', models.TextField()),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
