# Generated by Django 4.2.10 on 2024-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0005_rename_product_description_finalgoods_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgoods',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
