# Generated by Django 4.2.10 on 2024-02-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0007_alter_finalgoods_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgoods',
            name='invoice_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
