# Generated by Django 4.2.10 on 2024-02-12 17:12

from django.db import migrations, models
import pytz.tzinfo


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0007_alter_productionmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmodel',
            name='created_at',
            field=models.DateTimeField(default=pytz.tzinfo.DstTzInfo.localize),
        ),
        migrations.AlterField(
            model_name='productionmodel',
            name='updated_at',
            field=models.DateTimeField(default=pytz.tzinfo.DstTzInfo.localize),
        ),
    ]
