# Generated by Django 4.2.10 on 2024-02-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0008_alter_finalgoods_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgoods',
            name='item',
            field=models.CharField(choices=[('45 mm', '45 mm'), ('90 mm', '90 mm'), ('pencil', 'pencil')], max_length=10),
        ),
    ]
