# Generated by Django 4.2.10 on 2024-02-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0010_customer_alter_finalgoods_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.IntegerField(),
        ),
    ]
