# Generated by Django 4.2.10 on 2024-02-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0010_alter_productionmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
