# Generated by Django 4.2.10 on 2024-02-15 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0011_alter_productionmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer', models.CharField(max_length=50)),
                ('product_description', models.TextField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
