# Generated by Django 4.2.10 on 2024-02-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0013_auto_20240218_1912'),
    ]

    operations = [
    ]
