# Generated by Django 4.2.10 on 2024-02-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0013_alter_finalgoods_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgoods',
            name='product_description',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], max_length=10),
        ),
    ]
