# Generated by Django 4.2.10 on 2024-02-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0016_customer_alter_finalgoods_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_age',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
