# Generated by Django 4.2.10 on 2024-02-19 06:12

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('cns_app', '0017_customer_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=address.models.AddressField(default=2, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
            preserve_default=False,
        ),
    ]
