# Generated by Django 4.2.10 on 2024-02-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0018_customer_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_age',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_state',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(max_length=100),
        ),
    ]
