# Generated by Django 4.2.10 on 2024-02-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0019_remove_customer_customer_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_city',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
