# Generated by Django 4.2.10 on 2024-02-19 09:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0021_alter_customer_customer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('online', 'online')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], max_length=20)),
                ('payment_dues', models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cns_app.customer')),
            ],
        ),
    ]
