# Generated by Django 4.2.10 on 2024-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0022_paymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
