# Generated by Django 4.2.10 on 2024-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0023_paymentmodel_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=12),
            preserve_default=False,
        ),
    ]
