# Generated by Django 4.2.10 on 2024-02-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0024_alter_paymentmodel_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalgoods',
            name='discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgoods',
            name='gst',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
