# Generated by Django 4.2.10 on 2024-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0026_finalgoods_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='payment_dues',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_dues',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
