# Generated by Django 4.2.10 on 2024-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0027_remove_paymentmodel_payment_dues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], editable=False, max_length=20),
        ),
    ]
