# Generated by Django 4.2.10 on 2024-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0028_alter_customer_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('paid', 'PAID')], editable=False, max_length=20),
        ),
    ]
