# Generated by Django 4.2.10 on 2024-02-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cns_app', '0030_remove_finalgoods_item_finalgoods_item_45mm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalgoods',
            old_name='quantity',
            new_name='item_45mm_quantity',
        ),
        migrations.RenameField(
            model_name='finalgoods',
            old_name='rate',
            new_name='item_45mm_rate',
        ),
        migrations.AddField(
            model_name='finalgoods',
            name='item_90mm_quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgoods',
            name='item_90mm_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgoods',
            name='item_pencil_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgoods',
            name='item_pencil_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgoods',
            name='total_45mm',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgoods',
            name='total_90mm',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalgoods',
            name='total_pencil',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
